# Compile Firmware on Travis CI
# By Simon Peter
# Roughly based on https://github.com/prusa3d/Prusa-Firmware/issues/29 and
# https://learn.adafruit.com/continuous-integration-arduino-and-you/testing-your-project

language: c

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.3-linux64.tar.xz
  - tar xf arduino-*-linux64.tar.xz
  - find arduino-*/ -name platform.local.txt -delete

script:
  - arduino-*/arduino --pref build.path=. --verify --verbose-build --board arduino:avr:mega:cpu=atmega2560 $(readlink -f RF-100/RF-100.ino)
  - ls .
  - zip -r rf100_fw_$(git rev-parse --short HEAD).zip *.ino.hex *.pdf
  - # Create custom Cura AppImage with our printer definition preinstalled
  - export VERSION=2.7.0-BETA
  - wget -q -c "http://software.ultimaker.com/Cura_open_beta/Cura-$VERSION.AppImage"
  - sudo mount Cura-$VERSION.AppImage /mnt -o loop,ro
  - sudo cp -r /mnt Cura.AppDir
  - sudo chown -R $USER Cura.AppDir/
  - # mv Cura.AppDir/usr/bin/resources/definitions/fdm* .
  - # rm Cura.AppDir/usr/bin/resources/definitions/* Cura.AppDir/usr/bin/resources/variants/* Cura.AppDir/usr/bin/resources/extruders/*
  - # mv fdm* Cura.AppDir/usr/bin/resources/definitions/
  - wget https://github.com/probonopd/RF100-Firmware/raw/community/cura/renkforce_rf100xl.def.json
  - rm Cura.AppDir/usr/bin/resources/definitions/renkforce*
  - mv renkforce_rf100xl.def.json Cura.AppDir/usr/bin/resources/definitions/
  - file Cura.AppDir/.DirIcon 
  - mkdir -p Cura.AppDir/usr/share/icons/hicolor/128x128/apps
  - cp Cura.AppDir/.DirIcon Cura.AppDir/usr/share/icons/hicolor/128x128/apps/cura.png
  - sed -i -e 's|^Icon=.*|Icon=cura|g' Cura.AppDir/cura.desktop 
  - wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod a+x appimagetool-x86_64.AppImage 
  - cp Cura.AppDir/.DirIcon Cura.AppDir/cura.png
  - sed -i -e 's|^Name=.*|Name=Cura for Renkforce RF100|g' Cura.AppDir/cura.desktop 
  - ./appimagetool-x86_64.AppImage ./Cura.AppDir/

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh rf100_fw_*.zip Cura_for_Renkforce_RF100*.AppImage
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
