# Compile Firmware on Travis CI
# By Simon Peter
# Roughly based on https://github.com/prusa3d/Prusa-Firmware/issues/29 and
# https://learn.adafruit.com/continuous-integration-arduino-and-you/testing-your-project

language: c

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.3-linux64.tar.xz
  - tar xf arduino-*-linux64.tar.xz
  - find arduino-*/ -name platform.local.txt -delete

script:
  - arduino-*/arduino --verify --verbose-build --board arduino:avr:mega:cpu=atmega2560 $(readlink -f RF-100/RF-100.ino)
  - find /tmp -name RF-100.cpp.hex -exec cp {} . \;
  - zip -r rf100_fw_$(git rev-parse --short HEAD).zip RF-100.cpp.hex *.pdf
  - curl --upload-file rf100_fw_$(git rev-parse --short HEAD).zip https://transfer.sh/rf100_fw_$(git rev-parse --short HEAD).zip
